// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createMockSupabaseClient() {
  console.warn(
    "[Supabase] Running with mock Supabase client. To persist data or use authentication, connect Supabase in Lovable Cloud.",
  );

  const mockHandler: ProxyHandler<object> = {
    get(target, prop, receiver) {
      if (prop === "then") {
        return (resolve: (val: unknown) => void) => resolve({ data: [], error: null });
      }

      if (prop === "auth") {
        return {
          onAuthStateChange: (cb: (event: string, session: null) => void) => {
            // Call immediately with no session
            setTimeout(() => {
              try {
                cb("INITIAL_SESSION", null);
              } catch (e) {
                console.error(e);
              }
            }, 0);
            return {
              data: {
                subscription: {
                  unsubscribe: () => {},
                },
              },
            };
          },
          getSession: async () => ({ data: { session: null }, error: null }),
          getUser: async () => ({ data: { user: null }, error: null }),
          signInWithPassword: async () => {
            console.warn("[Supabase Mock] signInWithPassword called");
            return {
              data: { user: null, session: null },
              error: new Error(
                "Supabase is not configured. Please connect Supabase in Lovable Cloud.",
              ),
            };
          },
          signUp: async () => {
            console.warn("[Supabase Mock] signUp called");
            return {
              data: { user: null, session: null },
              error: new Error(
                "Supabase is not configured. Please connect Supabase in Lovable Cloud.",
              ),
            };
          },
          signInWithOAuth: async () => {
            console.warn("[Supabase Mock] signInWithOAuth called");
            return {
              data: {},
              error: new Error(
                "Supabase is not configured. Please connect Supabase in Lovable Cloud.",
              ),
            };
          },
          signOut: async () => ({ error: null }),
        };
      }

      // If they try to access a function, e.g. .from("table") or similar chain
      return (..._args: unknown[]) => {
        return new Proxy({}, mockHandler);
      };
    },
  };

  return new Proxy({}, mockHandler) as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    console.warn(
      `[Supabase] Missing Supabase environment variable(s): ${missing.join(", ")}. Falling back to mock client to prevent crash.`,
    );
    return createMockSupabaseClient();
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (error) {
    console.error("[Supabase] Failed to initialize real Supabase client:", error);
    return createMockSupabaseClient();
  }
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
