// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createMockSupabaseAdminClient() {
  console.warn(
    "[Supabase] Server-side running with mock Supabase admin client. Connect Supabase in Lovable Cloud to enable server-side admin operations.",
  );

  const mockHandler: ProxyHandler<object> = {
    get(target, prop, receiver) {
      if (prop === "then") {
        return (resolve: (val: unknown) => void) => resolve({ data: [], error: null });
      }

      if (prop === "auth") {
        return {
          getSession: async () => ({ data: { session: null }, error: null }),
          getUser: async () => ({ data: { user: null }, error: null }),
          getClaims: async () => ({ data: {}, error: null }),
        };
      }

      // Chainable fallback
      return (..._args: unknown[]) => {
        return new Proxy({}, mockHandler);
      };
    },
  };

  return new Proxy({}, mockHandler) as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    console.warn(
      `[Supabase] Missing Supabase environment variable(s) for Admin: ${missing.join(", ")}. Falling back to mock admin client to prevent crash.`,
    );
    return createMockSupabaseAdminClient();
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  } catch (error) {
    console.error("[Supabase] Failed to initialize real Supabase admin client:", error);
    return createMockSupabaseAdminClient();
  }
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
